[package]
name = "broccoli"
version = "0.6.2"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
description = "broadphase collision detection algorithms"
license = "MIT/Apache-2.0"
repository = "https://github.com/tiby312/broccoli"
keywords = ["tree", "kdtree","broadphase","space-partitioning","no_std"]
readme = "README.md"
edition = "2018"


[workspace]
members = [ "demo","report/data_gen"]

[dev-dependencies]
dists = {git="https://github.com/tiby312/dists.git"}

[dependencies]
is_sorted = "0.1"
itertools = "0.9"
rayon = "1.5"
compt = "1.9"
axgeom = {version="1.9",default-features = false}
pdqselect = "0.1"
unchecked_unwrap = "2.0.2"


[package.metadata.docs.rs]
# This sets the default target to `x86_64-unknown-linux-gnu`
# and only builds that target
targets = ["x86_64-unknown-linux-gnu"]

#[profile.release]
#debug = true

#[patch.crates-io]
#axgeom={path="../axgeom"}
